//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaraMemo.Shell {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaraMemo.Shell.MainResources", typeof(MainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   作業を開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActiveButtonTitle {
            get {
                return ResourceManager.GetString("ActiveButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   稼働時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActiveTimeSumTitle {
            get {
                return ResourceManager.GetString("ActiveTimeSumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AfkStatusActive {
            get {
                return ResourceManager.GetString("AfkStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   離席中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AfkStatusAfk {
            get {
                return ResourceManager.GetString("AfkStatusAfk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   休憩中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AfkStatusBreak {
            get {
                return ResourceManager.GetString("AfkStatusBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業ステータス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AfkStatusTitle {
            get {
                return ResourceManager.GetString("AfkStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AFK時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AfkTimeSumTitle {
            get {
                return ResourceManager.GetString("AfkTimeSumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   休憩を開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BreakButtonTitle {
            get {
                return ResourceManager.GetString("BreakButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   休憩時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BreakTimeSumTitle {
            get {
                return ResourceManager.GetString("BreakTimeSumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   記録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordHeaderTitle {
            get {
                return ResourceManager.GetString("RecordHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再読み込み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReloadButtonToolTip {
            get {
                return ResourceManager.GetString("ReloadButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リロードしました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReloadMessage {
            get {
                return ResourceManager.GetString("ReloadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステータス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusHeaderTitle {
            get {
                return ResourceManager.GetString("StatusHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   だらめも に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
